Repository dailykit/HERN-app, pull requests merged in 2022-07, with the labels that each got.

#13 feat: scroll products to specific category
  screens/menu/index.js
Labels: enhancement

#15 feat: created Choose Fulfillment Screen after splash screen
  assets/deliveryIcon.js
  assets/pickupIcon.js
  brandConfig.json
  components/header.js
  components/location/locationSelector.js
  components/userInfo.js
  navigation/index.js
  screens/cart/fulfillmentSection/Delivery.js
  screens/cart/fulfillmentSection/Pickup.js
  screens/cart/fulfillmentSection/index.js
  screens/cart/index.js
  screens/fulfillment/index.js
  screens/home/index.js
Labels: bug, enhancement

#16 feat: counter button on product card
  components/modifierPopup.js
  components/product.js
Labels: enhancement

#17 fix: fulfillment options label taken from DB from orderTabs
  screens/fulfillment/index.js
Labels: bug

#18 fix: made skip button visibility on login page config based
  brandConfig.json
  screens/login/otp/index.js
Labels: enhancement

#19 Fix/safe area view
  App.js
  components/location/locationSelector.js
  context/cart.js
  screens/account/index.js
  screens/cart/index.js
  screens/home/index.js
  screens/login/index.js
  screens/menu/index.js
  screens/myOrders/index.js
  screens/paymentOptions/index.js
  screens/product/index.js
  screens/productSearch/index.js
  screens/refineLocation/index.js
  yarn.lock
Labels: bug

#20 feat: added loaders on all screens
  assets/loaders/index.js
  assets/loaders/spinner.js
  components/location/locationSelector.js
  components/modifierPopup.js
  components/payButton.js
  components/paymentOptionRenderer.js
  components/product.js
  lib/payment.js
  navigation/index.js
  screens/account/index.js
  screens/account/subscreen/loyaltyScreen.js
  screens/account/subscreen/offers.js
  screens/account/subscreen/wallet.js
  screens/cart/cartCard.js
  screens/cart/index.js
  screens/login/index.js
  screens/menu/index.js
  screens/myOrders/index.js
  screens/myOrders/subscreen/orderDetail.js
  screens/myOrders/subscreen/orderTracking.js
  screens/product/index.js
Labels: enhancement

#21 fix: Updated subscription query for My Orders page, to fetch null createdAt orders will be at last
  graphql/subscriptions.js
  screens/myOrders/subscreen/orderDetail.js
Labels: bug

#22 Feat/get app config from database
  assets/loaders/spinner.js
  brandConfig.json
  components/addCard.js
  components/button.js
  components/counterButton.js
  components/header.js
  components/location/delivery.js
  components/location/pickup.js
  components/modifierCategory.js
  components/modifierOption.js
  components/modifierPopup.js
  components/payButton.js
  components/paymentOptionRenderer.js
  components/product.js
  components/userInfo.js
  graphql/queries.js
  graphql/subscriptions.js
  lib/config.js
  screens/account/header.js
  screens/account/subscreen/wallet.js
  screens/cart/address.js
  screens/cart/cartCard.js
  screens/cart/cartHeader.js
  screens/cart/cartItemList.js
  screens/cart/emptyCart.js
  screens/cart/fulfillmentSection/Delivery.js
  screens/cart/fulfillmentSection/Pickup.js
  screens/cart/index.js
  screens/fulfillment/index.js
  screens/home/index.js
  screens/login/otp/index.js
  screens/login/otp/mobileNumberForm.js
  screens/login/otp/otpForm.js
  screens/menu/index.js
  screens/myOrders/index.js
  screens/myOrders/subscreen/component/deliveryProgressBar.js
  screens/myOrders/subscreen/component/deliveryTrackingOnMap.js
  screens/myOrders/subscreen/orderDetail.js
  screens/myOrders/subscreen/orderTracking.js
  screens/paymentOptions/paymentOptionsHeader.js
  screens/product/index.js
Labels: bug, enhancement

#24 tweak: added loading states into login flow
  assets/loaders/spinner.js
  screens/login/otp/index.js
  screens/login/otp/mobileNumberForm.js
  screens/login/otp/otpForm.js
Labels: enhancement

#25 fix: handle razorpay failed status
  lib/payment.js
Labels: bug

#26 fix: get app settings with query instead of subscription, and made brand domain env based
  graphql/queries.js
  graphql/subscriptions.js
  lib/config.js
  utils/get_env.js
Labels: bug

#29 Feat/add video feature to promotion carousal
  assets/splash.png
  package.json
  screens/home/index.js
  screens/home/promotionCarousel.js
  screens/menu/index.js
  yarn.lock
Labels: enhancement

#30 Fix/close login popup after navigation on cart page
  components/userInfo.js
  screens/cart/index.js
Labels: bug

#44 Feat/added countdown into resend otp and payment modal
  components/payButton.js
  components/paymentProcessingModal.js
  components/timer.js
  components/userInfo.js
  lib/payment.js
  screens/cart/index.js
  screens/login/otp/otpForm.js
  screens/paymentOptions/index.js
  utils/useRazorpay.js
Labels: bug, enhancement

#45 Tweaks/resend otp tweaks
  screens/account/index.js
  screens/login/otp/otpForm.js
Labels: bug

#48 Fix/added permission condition for notification token
  .gitignore
  app.json
  screens/login/otp/index.js
  utils/useSession.js
Labels: bug

#49 Fix/font weights
  assets/loaders/spinner.js
  components/button.js
  components/counterButton.js
  components/floatingMenu.js
  components/header.js
  components/helperBar.js
  components/location/addressInfo.js
  components/location/delivery.js
  components/location/locationSelector.js
  components/location/pickup.js
  components/location/storeList.js
  components/modifierCategory.js
  components/modifierOption.js
  components/modifierPopup.js
  components/paymentOptionRenderer.js
  components/paymentProcessingModal.js
  components/product.js
  components/productCategory.js
  components/userInfo.js
  globalStyle.js
  navigation/bottomNavbar.js
  screens/account/index.js
  screens/account/subscreen/header.js
  screens/account/subscreen/loyaltyScreen.js
  screens/account/subscreen/offers.js
  screens/account/subscreen/wallet.js
  screens/cart/address.js
  screens/cart/cartBillingDetails.js
  screens/cart/cartCard.js
  screens/cart/cartHeader.js
  screens/cart/fulfillmentSection/Delivery.js
  screens/cart/fulfillmentSection/Pickup.js
  screens/cart/index.js
  screens/fulfillment/index.js
  screens/home/index.js
  screens/login/otp/mobileNumberForm.js
  screens/login/otp/otpForm.js
  screens/menu/index.js
  screens/myOrders/cartItem.js
  screens/myOrders/index.js
  screens/myOrders/subscreen/component/billingDetails.js
  screens/myOrders/subscreen/component/deliveryProgressBar.js
  screens/myOrders/subscreen/orderDetail.js
  screens/myOrders/subscreen/orderTracking.js
  screens/product/index.js
  screens/productSearch/index.js
  screens/refineLocation/index.js
Labels: enhancement

#50 feat: added users saved address list into Location Selector
  components/location/delivery.js
  components/location/googlePlaceAutoComplete.js
  components/location/userAddressList.js
  context/index.js
  screens/refineLocation/index.js
Labels: enhancement

#51 tweak: fetch prdoucts in context
  components/product.js
  context/onDemandMenu.js
  package.json
  screens/menu/index.js
  yarn.lock
Labels: enhancement

#52 fix: added default image
  screens/cart/cartCard.js
  screens/product/index.js
Labels: bug

#53 feat: optimistic response on user info, fulfillment info, address
  components/userInfo.js
  graphql/mutations.js
  screens/cart/address.js
  screens/cart/fulfillmentSection/Delivery.js
  screens/cart/fulfillmentSection/Pickup.js
  screens/cart/index.js
  screens/refineLocation/index.js
Labels: enhancement

#54 fix: change modal modifiers into bottom sheets, and added skeleton into trending products
  assets/loaders/productsLoader.js
  components/modifierPopup.js
  components/skeleton.js
  screens/cart/cartCard.js
  screens/home/index.js
  screens/product/index.js
Labels: bug

#101 Fix/cart screen
  assets/vector.js
  components/counterButton.js
  components/location/pickup.js
  components/location/storeList.js
  components/userInfo.js
  context/cart.js
  screens/cart/address.js
  screens/cart/cartBillingDetails.js
  screens/cart/cartCard.js
  screens/cart/cartHeader.js
  screens/cart/cartItemList.js
  screens/cart/emptyCart.js
  screens/cart/fulfillmentSection/Delivery.js
  screens/cart/fulfillmentSection/Pickup.js
  screens/cart/fulfillmentSection/index.js
  screens/cart/fulfillmentSection/timeSlots.js
  screens/cart/index.js
Labels: bug, enhancement

#102 fix: changed spash screen image with more clear image
  assets/splash.png
  context/cart.js
Labels: bug

#103 Fix/fixed errors
  components/userInfo.js
  screens/cart/fulfillmentSection/Delivery.js
  screens/cart/fulfillmentSection/Pickup.js
  screens/menu/index.js
  screens/myOrders/index.js
  screens/productSearch/index.js
Labels: bug

#105 feat: added video caching functionality
  components/cacheVideo.js
  package.json
  screens/home/promotionCarousel.js
Labels: enhancement

#108 Fix/fix pending issues
  components/floatingMenu.js
  components/location/locationSelector.js
  components/product.js
  components/productCategory.js
  navigation/bottomNavbar.js
  package-lock.json
  screens/fulfillment/index.js
  screens/product/index.js
  yarn.lock
Labels: UI

#111 Fix/errors
  components/location/delivery.js
  components/location/googlePlaceAutoComplete.js
  screens/cart/fulfillmentSection/Delivery.js
  screens/cart/fulfillmentSection/Pickup.js
  screens/cart/fulfillmentSection/index.js
  screens/refineLocation/index.js
Labels: bug

#114 fix: split razorpay payment methods into diffrent payment options
  components/paymentOptionRenderer.js
  components/paymentProcessingModal.js
  graphql/subscriptions.js
  screens/account/subscreen/wallet.js
  utils/getRazorpayOptions.js
Labels: bug

#116 fix: redirected to product after setting location with which location selector was opened
  components/location/delivery.js
  components/location/locationSelector.js
  components/location/pickup.js
  components/location/storeList.js
  components/product.js
  screens/refineLocation/index.js
Labels: enhancement

#117 fix: prev address remains in searchbar after clicking on my location button
  components/location/googlePlaceAutoComplete.js
Labels: enhancement

#118 Fix/issues
  App.js
  navigation/index.js
  screens/menu/index.js
Labels: bug

#119 Fix/fix UI issues
  components/modifierPopup.js
  components/paymentProcessingModal.js
  components/product.js
  components/userInfo.js
  screens/account/index.js
  screens/cart/address.js
  screens/cart/cartCard.js
  screens/cart/cartItemList.js
  screens/login/otp/mobileNumberForm.js
  screens/login/otp/otpForm.js
  screens/product/index.js
Labels: UI, improvement

#120 fix: updated splash screen with less size, and updated maps library
  assets/splash.png
  package.json
  screens/cart/cartCard.js
  screens/cart/cartItemList.js
  yarn.lock
Labels: bug

#121 fix: only one item shown in each category
  components/product.js
Labels: bug

#122 fix: cart deleted on single item change
  context/cart.js
Labels: bug
